version: 2.1

orbs:
 android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout
      - run:
          command: ./gradlew test jacocoRootReport buildDebug
      - run:
          command: >-
              bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java -r
              build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
